<?php
/**
 * Maintenance Grids
 *
 * @category    Forkel
 * @package     Forkel_Grids
 * @copyright   Copyright (c) 2015 Tobias Forkel (http://www.tobiasforkel.de)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<div id="messages">
    <ul class="messages">
        <li class="notice-msg"><?php echo sprintf('Lorem ipsum ( %s ) dolor sit amet, sea veritus similique ex. Ex ridens propriae vulputate nec. Mea quaestio dissentiet theophrastus an. Id ius elitr complectitur.', $this->getDate()); ?></li>
    </ul>
</div>
