<?php
/**
 * Maintenance Grids
 *
 * @category    Forkel
 * @package     Forkel_Grids
 * @copyright   Copyright (c) 2015 Tobias Forkel (http://www.tobiasforkel.de)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
    function openPopup() {

        var url = '<?php echo $this->getUrl('*/*/popup') ?>?';

        if ($('browser_window') && typeof(Windows) != 'undefined') {
            Windows.focus('browser_window');
            return;
        }

        var dialogWindow = Dialog.info(null, {
            closable: true,
            resizable: false,
            draggable: true,
            className: 'magento',
            windowClassName: 'popup-window',
            title: '<?php echo $this->getTitle() ?>',
            top: 50,
            width: 640,
            height: 480,
            zIndex: 1000,
            recenterAuto: false,
            hideEffect: Element.hide,
            showEffect: Element.show,
            id: 'browser_window',
            url: url,
            onClose: function (param, el) {
                alert('onClose');
            }
        });
    }

    function closePopup() {
        Windows.close('browser_window');
    }
</script>
