<?php
/**
 * Forkel Grids
 *
 * @category    Forkel
 * @package     Forkel_Grids
 * @copyright   Copyright (c) 2015 Tobias Forkel (http://www.tobiasforkel.de)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php
$numColumns = sizeof($this->getColumns());
?>
<?php if($this->getCollection()): ?>
<div class="grid np">
<table cellspacing="0" style="border:0;" id="<?php echo $this->getId() ?>_table">
    <?php foreach ($this->getColumns() as $_column): ?>
    <col <?php echo $_column->getHtmlProperty() ?> />
    <?php endforeach; ?>
    <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
        <thead>
            <?php if ($this->getHeadersVisibility()): ?>
                <tr class="headings">
                <?php foreach ($this->getColumns() as $_column): ?>
                    <th <?php echo $_column->getHeaderHtmlProperty() ?>><span class="nobr"><?php echo $_column->getHeaderHtml() ?></span></th>
                <?php endforeach; ?>
                </tr>
            <?php endif; ?>
        </thead>
    <?php endif; ?>
    <tbody>
    <?php if (($this->getCollection()->getSize()>0) && (!$this->getIsCollapsed())): ?>
    <?php foreach ($this->getCollection() as $_index=>$_item): ?>
        <tr title="<?php echo $this->getRowId($_item) ?>">
        <?php $i=0;foreach ($this->getColumns() as $_column): ?>
            <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i==$numColumns?'last':'' ?>"><?php echo (($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') ?></td>
        <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    <?php elseif ($this->getEmptyText()): ?>
        <tr>
            <td class="empty-text <?php echo $this->getEmptyTextClass() ?>" colspan="100"><?php echo $this->getEmptyText() ?></td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>
</div>
<?php endif ?>
